#!/usr/bin/env bash
#
# volbash - simple wpctl wrapper
#
# Copyright (C) 2025 Xavier Moffett <sapphirus@azorium.net>
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -eEo pipefail

# Meta
VERSION="1.0"
NAME="${0##*/}"

# Declare input and output sinks
SOURCE="@DEFAULT_AUDIO_SOURCE@"
OUTPUT="@DEFAULT_AUDIO_SINK@"

main() {
    local action bypass
    local sink="$OUTPUT"
    local delta=5

    while (($#)); do
        case $1 in
        --bypass)
            bypass=1
            ;;
        --source | -s)
            sink="$SOURCE"
            ;;
        --delta | -d)
            shift
            delta=$1
            ;;
        --help | -h)
            help
            ;;
        --version | -v)
            version
            ;;
        -*)
            invalid_option "$1"
            ;;
        *)
            action="$1"
            ;;
        esac
        shift
    done

    case $action in
    up | down)
        adjust "$delta"
        ;;
    mute | unmute | toggle)
        toggle
        ;;
    *)
        invalid_option
        ;;
    esac
}

toggle() {
    if [[ -z $action ]]; then
        wpctl set-mute "$sink" toggle
    else
        wpctl set-mute "$sink" "$([[ "$action" == "mute" ]] && echo 1 || echo 0)"
    fi
}

adjust() {
    local delta vol op 

    # Check for valid input value 
    if [[ ! $1 -gt 0 ]]; then
        echo "error: Delta value must be a positive integer."
        exit 2 
    fi

    # Ascertain the volume level by parsing wpctl's output
    vol=$(v="$(wpctl get-volume "$sink")"; echo "${v#* }")
    vol=$([[ ${vol%.*} -gt 0 ]] && echo "${vol%.*}" || echo)${vol#*.}

    # Designate an arithmetic operator for the operation
    op=$([[ "$action" == "up" ]] && echo "+" || echo "-")
    delta="${1}%$op"

    # Check if the volume increment exceeds 100 and override
    # the delta if the bypass option has not been specified.
    if [[ -z $bypass ]] && [[ $(("$vol" "$op" "$1")) -gt 100 ]]; then
        delta="100%"
    fi

    wpctl set-volume "$sink" "$delta"
}

invalid_option() {
    if [[ -z $1 ]]; then
        echo "error: Operation not specified"
    else
        echo "error: Invalid option '$1'"
    fi

    echo "Try '$ volbash --help' for further information."
    exit 1
}

version() {
    echo -e "$NAME $VERSION - simple wpctl wrapper
Copyright (C) 2025 Xavier Moffett\n
Distributed under the MIT License\n"
    exit
}

help() {
    echo -e "Usage: $NAME [OPERATION] | [OPTION]

Operations:
    up                          Increment volume
    down                        Decrement volume
    mute                        Mute volume
    unmute                      Unmute volume
    toggle                      Toggle mute
 
Options:
    --delta, -d VALUE           Set delta value
    --source, -s                Apply operation to source
    --bypass                    Allow increments past 100%
    --version                   Print version information
    --help                      Print this help and exit
 
All operations apply to the default sink only.\n"
    exit
}

main "$@"

# vim:set ts=4 sw=4 et:1
